package com.example.adkagent

import androidx.test.ext.junit.runners.AndroidJUnit4
import com.example.adkagent.agent.CloudScreenerAgent
import com.google.adk.kt.models.LlmRequest
import com.google.adk.kt.models.LlmResponse
import com.google.adk.kt.models.Model
import com.google.adk.kt.runners.InMemoryRunner
import com.google.adk.kt.types.Content
import com.google.adk.kt.types.FunctionCall
import com.google.adk.kt.types.Part
import com.google.adk.kt.types.Role
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.test.runTest
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class StockAgentAutomationTest {

    /**
     * A mock model that correctly handles the sequential dependency of your stock tools.
     * Use the exact tool names (function names) as generated by KSP.
     */
    class MockModel(override val name: String = "mock-model") : Model {
        private var callCount = 0

        override fun generateContent(request: LlmRequest, stream: Boolean): Flow<LlmResponse> {
            callCount++

            val responseContent = when (callCount) {
                1 -> {
                    // Turn 1: Model realizes it needs data first. Calls the fetch tool.
                    Content(
                        role = Role.MODEL,
                        parts = listOf(Part(functionCall = FunctionCall(name = "getStockNews", args = mapOf("ticker" to "GOOGL"))))
                    )
                }
                2 -> {
                    // Turn 2: Fetch tool returned data. Now call the analysis tool.
                    Content(
                        role = Role.MODEL,
                        parts = listOf(Part(functionCall = FunctionCall(name = "analyzeStockNews", args = mapOf("rawNewsData" to "MOCK_NEWS_DATA"))))
                    )
                }
                3 -> {
                    // Turn 3: Analysis complete. Call the communication tool.
                    Content(
                        role = Role.MODEL,
                        parts = listOf(Part(functionCall = FunctionCall(name = "sendEmailToUser", args = mapOf("ticker" to "GOOGL"))))
                    )
                }
                else -> {
                    // Final Turn: All tools completed. Provide the concluding summary to the user.
                    Content(
                        role = Role.MODEL,
                        parts = listOf(Part(text = "Analysis for GOOGL completed and summarized news emailed."))
                    )
                }
            }

            return flowOf(LlmResponse(content = responseContent))
        }
    }

    @Test
    fun testStockAnalysisPipelineExecution() = runTest {
        val mockModel = MockModel()

        // Setup: Use the CloudScreenerAgent with our mock model. 
        // The CloudScreenerAgent class already includes StockTools.generatedTools().
        val testAgent = CloudScreenerAgent(mockModel).agent
        val testRunner = InMemoryRunner(testAgent)

        val userPrompt = "Check the recent news headlines for GOOGL, summarize them, and email it to me."

        val events = mutableListOf<com.google.adk.kt.events.Event>()
        testRunner.runAsync(
            userId = "test-user",
            sessionId = "test-session",
            newMessage = Content.fromText(Role.USER, userPrompt)
        ).collect { event ->
            events.add(event)
        }

        // Assert against the exact tool names (function names) as registered in the agent
        val fetchedNews = events.any { event -> event.functionCalls().any { it.name == "getStockNews" } }
        val analyzedNews = events.any { event -> event.functionCalls().any { it.name == "analyzeStockNews" } }
        val emailSent = events.any { event -> event.functionCalls().any { it.name == "sendEmailToUser" } }

        assertTrue("Fail: Agent omitted fetching stock data.", fetchedNews)
        assertTrue("Fail: Agent omitted summarizing data.", analyzedNews)
        assertTrue("Fail: Agent failed to route the final email.", emailSent)

        // Validate the final textual resolution streamed back to your UI layer
        val finalResponse = events.find { it.isFinalResponse }
        assertTrue("Fail: Agent never reached a conclusion state.", finalResponse != null)
        assertTrue("Fail: Final response text content is incorrect.",
            finalResponse?.content?.parts?.any { it.text?.contains("emailed") == true } == true)
    }
}
